name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: '1.12.1.1550'

    - name: Run tests
      run: clojure -X:test

    - name: Run cljs tests
      run: clojure -M:test-cljs
