name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: '1.11.1.1347'
    - name: Run tests
      run: clojure -X:test
    - name: Run cljs tests
      run: clojure -M:test-cljs
